# Generated by Django 3.0.3 on 2020-03-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300)),
                ('item_desc', models.CharField(max_length=500)),
                ('item_price', models.IntegerField()),
                ('item_cuisine', models.CharField(max_length=200)),
                ('item_type', models.CharField(max_length=200)),
                
            ],
        ),
    ]
