# Generated by Django 3.0.3 on 2020-03-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_food_item_taste'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='item_ingredients',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
