# Generated by Django 3.0.3 on 2020-03-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_food_item_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='item_option',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
