# Generated by Django 3.0.3 on 2020-03-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_food_item_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='item_image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
