# Generated by Django 3.0.3 on 2020-03-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_food_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_fname', models.CharField(max_length=500)),
                ('u_lname', models.CharField(max_length=500)),
                ('u_username', models.CharField(max_length=500)),
                ('u_password', models.CharField(max_length=400)),
                ('u_email', models.CharField(max_length=300)),
                ('u_address', models.CharField(max_length=500)),
                ('u_foodp', models.CharField(max_length=500)),
            ],
        ),
    ]
