# Generated by Django 3.0.3 on 2020-04-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
