# Generated by Django 3.0.3 on 2020-04-26 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0009_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('text', models.TextField()),
                ('food', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='foodapp.Food')),
            ],
        ),
    ]
