# Generated by Django 3.0.3 on 2020-04-27 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodapp', '0012_auto_20200427_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment1',
            name='username',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment1',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
