# Generated by Django 3.0.3 on 2020-04-27 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0013_auto_20200427_1237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment1',
        ),
    ]
